const CONFIG = {
  TELEGRAM_TOKEN: '1234567890:ABC-REAL-BOT-TOKEN-HERE',
  YOUTUBE_API_KEY: 'YOUR_YOUTUBE_API_KEY',
  UPLOADS_PLAYLIST_ID: 'YOUR_YOUTUBE_PLAYLIST_ID',
  CACHE_DURATION: 300 // 5 minutes in seconds
};